config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'appointments#index'
  resources :appointments, only: %w(index new create edit update) do
    collection do
      get :past
    end
  end

  namespace :api do
    resources :appointments, only: %w(index create) do
      collection do
        get :by_date
      end
    end
  end

  resources :user_statistics, only: :index
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  PENDING = 'pending'
  CONFIRMED = 'confirmed'
  CANCELLED = 'cancelled'
  DURATION = 1.hours
  AVAILABLE_STATUSES = [PENDING, CONFIRMED, CANCELLED]

  belongs_to :user
  has_many :reminders, inverse_of: :appointment
  accepts_nested_attributes_for :reminders

  scope :incoming, -> { where('start_at > ?', Time.current).includes(:reminders).order(:start_at) }
  scope :past, -> { where('start_at < ?', Time.current).includes(:reminders).order(start_at: :desc) }
  scope :filter_by_status, -> status do
    where(status: status) if AVAILABLE_STATUSES.include?(status)
  end
  scope :filter_by_date, -> date do
    if parsed_date = date && Date.parse(date)
      where(start_at: parsed_date..parsed_date + 1.day)
    end
  end

  validates :user, :start_at, presence: true
  before_validation :has_valid_start_time?, on: :create

  def cancelled?
    status == CANCELLED
  end

  def to_builder
    Jbuilder.new do |appointment|
      appointment.(self, :id, :status, :description, :start_at)
    end
  end

  private

  def has_valid_start_time?
    return if start_at.blank?

    errors.add(:start_at, :passed) if start_at.past?
    if Appointment.where.not(id: id).where(start_at: start_at - DURATION..start_at + DURATION, user: user).exists?
      errors.add(:start_at, :overlap)
    end
  end

end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  PENDING = 'pending'
  REMINDED = 'reminded'

  belongs_to :appointment, inverse_of: :reminders

  validates :appointment, :remind_at, presence: true

  before_validation :has_valid_start_time?, on: :create
  after_create :generate_remind_worker

  delegate :cancelled?, to: :appointment, prefix: true

  private

  def has_valid_start_time?
    return if remind_at.blank?

    errors.add(:remind_at, :passed) if remind_at.past?
    errors.add(:remind_at, :too_later) if appointment && appointment.start_at < remind_at
  end

  def generate_remind_worker
    RemindWorker.perform_at(remind_at, id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  CUSTOMER = 'customer'
  ADMIN = 'admin'

  has_many :appointments
  has_many :user_statistics

  before_create :generate_token

  def admin?
    role == ADMIN
  end

  private

  def generate_token
    charset = ('a'..'z').to_a + ('A'..'Z').to_a + ('0'..'9').to_a
    charset_length = charset.length
    self.token ||= loop do
      token = 20.times.inject('') { |s| s << charset[rand(charset_length)] }
      break token unless User.exists?(token: token)
    end
  end

end

app/models/user_statistic.rb
class UserStatistic < ActiveRecord::Base
  belongs_to :user
end

app/controllers/api/appointments_controller.rb
class Api::AppointmentsController < ApplicationController

  before_action :authenticate_user_using_x_auth_token!
  before_action :generate_user_statistic

  def index
    @appointments = @user.appointments.incoming.filter_by_status(params[:status])
    render json: { appointments: @appointments.map{ |a| appointment_to_json(a) } }
  end

  def by_date
    @appointments = @user.appointments.past.filter_by_status(params[:status]).filter_by_date(params[:date])
    render json: { appointments: @appointments.map{ |a| appointment_to_json(a) } }
  end

  def create
    @appointment = @user.appointments.new(appointment_params)
    if @appointment.save
      render json: { appointment: appointment_to_json(@appointment) }
    else
      respond_with_error "Cannot create appointment: #{@appointment.errors.full_messages}", :error
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:description, :start_at, reminders_attributes: [:remind_at, :description])
  end

  def respond_with_error(message, status)
    render json: { error: message }, status: status
  end

  def authenticate_user_using_x_auth_token!
    token = request.headers['X-Auth-Token']
         p "TOKEN: #{token}"
    @user = token && User.find_by_token(token)

    if @user
      sign_in @user, store: false
    else
      respond_with_error('Could not authenticate with the provided credentials.', :unauthorized)
    end
  end

  def appointment_to_json(appointment)
    appointment.to_builder.target!
  end

  def generate_user_statistic
    @user.user_statistics.create(params: params, api_method: action_name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  before_action :authenticate_user!
  before_action :load_appointment, only: %w(edit update)

  def index
    @appointments = current_user.appointments.incoming.filter_by_status(params[:status])
  end

  def past
    @appointments = current_user.appointments.past.filter_by_status(params[:status])
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = current_user.appointments.new(appointment_params)
    if @appointment.save
      redirect_to appointments_path
    else
      render :new
    end
  end

  def edit
    render
  end

  def update
    if @appointment.update(appointment_edit_params)
      redirect_to appointments_path
    else
      render :edit
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:description, :start_at, reminders_attributes: [:remind_at, :description])
  end

  def load_appointment
    @appointment = current_user.appointments.find(params[:id])
  end

  def appointment_edit_params
    params.require(:appointment).permit(:status)
  end


end

app/controllers/user_statistics_controller.rb
class UserStatisticsController < ApplicationController

  before_action :authenticate_user!
  before_action :check_permission

  def index
    @user_statistics = UserStatistic.joins(:user)
  end

  private

  def check_permission
    current_user.admin? || raise(ActionController::RoutingError.new('Not Found'))
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/_appointments.html.haml
.list-group
  - @appointments.each do |appointment|
    = link_to edit_appointment_path(appointment), class: 'list-group-item' do
      .row
        .col-md-2= I18n.l(appointment.start_at, format: :datetime)
        .col-md-7= appointment.description
        .col-md-2
          - appointment.reminders.each do |reminder|
            = I18n.l(reminder.remind_at, format: :datetime)
        .col-md-1
          .label.label-primary= appointment.status

app/views/appointments/_reminder_fields.html.haml
.nested-fields
  .form-group
    = f.label :description
    %br
    = f.text_area :description, class: 'form-control'

  .form-group
    = f.label :remind_at
    %br
    = f.datetime_select :remind_at, ampm: true, minute_step: 5, class: 'form-control'

  = link_to_remove_association "Remove reminder", f

app/views/appointments/edit.html.haml
.top-menu-links
  = link_to 'Appointments', appointments_path

= form_for(@appointment) do |f|
  - @appointment.errors.full_messages.each do |msg|
    %p.error-message= msg

  .form-group
    = f.label :status
    %br
    = f.select :status, Appointment::AVAILABLE_STATUSES
  .actions
    = f.submit 'Update', class: 'btn btn-primary'

app/views/appointments/index.html.haml
.top-menu-links
  = link_to 'New appointment', new_appointment_path
= link_to 'Past appointments', past_appointments_path

%ul.nav.nav-pills
  %li{ role: 'presentation' }
    = link_to 'All', appointments_path
  %li{ role: 'presentation' }
    = link_to 'Pending', appointments_path(status: 'pending')
  %li{ role: 'presentation' }
    = link_to 'Confirmed', appointments_path(status: 'confirmed')
  %li{ role: 'presentation' }
    = link_to 'Cancelled', appointments_path(status: 'cancelled')

= render 'appointments'

app/views/appointments/new.html.haml
.top-menu-links
  = link_to 'Appointments', appointments_path

= form_for(@appointment) do |f|
  - @appointment.errors.full_messages.each do |msg|
    %p.error-message= msg

  .form-group
    = f.label :description
    %br
    = f.text_area :description, class: 'form-control'

  .form-group
    = f.label :start_at
    %br
    = f.datetime_select :start_at, ampm: true, minute_step: 15, class: 'form-control'

  .form-group
    = f.label :reminders

    = f.fields_for :reminders do |reminder|
      = render 'reminder_fields', f: reminder

    .links
      = link_to_add_association 'Add reminder', f, :reminders

  .actions
    = f.submit 'Create', class: 'btn btn-primary'

app/views/appointments/past.html.haml
.top-menu-links
  = link_to 'Appointments', appointments_path

%ul.nav.nav-pills
  %li{ role: 'presentation' }
    = link_to 'All', past_appointments_path
  %li{ role: 'presentation' }
    = link_to 'Pending', past_appointments_path(status: 'pending')
  %li{ role: 'presentation' }
    = link_to 'Confirmed', past_appointments_path(status: 'confirmed')
  %li{ role: 'presentation' }
    = link_to 'Cancelled', past_appointments_path(status: 'cancelled')


= render 'appointments'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Appointments
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      - if current_user
        .navbar-text.navbar-right
          = button_to 'Logout', destroy_user_session_path, method: :delete, class: 'media'
        .navbar-text.navbar-right
          = link_to 'User Statistics', user_statistics_path, class: 'media'

      = yield

app/views/user_statistics/index.html.haml
- @user_statistics.each do |user_statistic|
  .row
    .col-md-2= user_statistic.user.token
    .col-md-1= I18n.l(user_statistic.created_at, format: :datetime)
    .col-md-1= user_statistic.api_method
    .col-md-4= user_statistic.params